SIIC/SIIC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
    path('', include('estoque.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SIIC/cadastros/urls.py
from django.urls import path
from .views import UsuarioUpdate, ProdutoUpdate
from .views import UsuarioDelete, ProdutoDelete
from .views import UsuarioList, CorCreate, TamanhoProdutoCreate, ProdutoCreate, ProdutoList, ProdutoDetalhes, produto_json, CategoriaCreate

# from .views import IndexView


urlpatterns = [
    # UPDATE -- OBTEM O ID ATRAVÉS DA URL
    path('editar/usuario/<int:pk>/',
         UsuarioUpdate.as_view(), name='editar-usuario'),
    path('editar/produto/<int:pk>', ProdutoUpdate.as_view(), name='editar-produto'),
    path('cadastrar/cor', CorCreate.as_view(), name='cadastrar-cor'),
    path('cadastrar/categoria', CategoriaCreate.as_view(),
         name='cadastrar-categoria'),
    path('cadastrar/tamanho', TamanhoProdutoCreate.as_view(),
         name='cadastrar-tamanho'),
    path('cadastrar/produto', ProdutoCreate.as_view(), name='cadastrar-produto'),
    # DELETE -- OBTEM O ID ATRAVÉS DA URL
    path('excluir/usuario/<int:pk>/',
         UsuarioDelete.as_view(), name='excluir-usuario'),
    path('excluir/produto/<int:pk>',
         ProdutoDelete.as_view(), name='excluir-produto'),

    # LISTAR BANCO
    path('listar/usuarios/', UsuarioList.as_view(), name='listar-usuarios'),
    path('listar/produtos/', ProdutoList.as_view(), name='listar-produtos'),
    path('detalhes/produtos/<int:pk>/', ProdutoDetalhes, name='detalhar-produto'),
    path('produto/<int:pk>/json/', produto_json, name='produto_json'),
]

SIIC/cadastros/models.py
from functools import total_ordering
from django.db import models
from django.contrib.auth.models import User
from django.urls.base import reverse_lazy
from usuarios.models import Usuario


# Create your models here.
# classe que define os atributos dos campos
# conforme o atributo da classe também valida os campos
# cada classe representa uma tabela na base de dados


class CorProduto(models.Model):
    cor_produto = models.CharField(
        max_length=50, verbose_name='Cor do produto', unique=True)

    class Meta:
        ordering = ['cor_produto']

    def __str__(self):
        return "{}".format(self.cor_produto)


class TamanhoProduto(models.Model):
    tamanho_produto = models.CharField(
        max_length=50, verbose_name='Tamanho do produto', unique=True)

    def __str__(self):
        return "{}".format(self.tamanho_produto)


class Produto(models.Model):
    nome_produto = models.CharField(
        max_length=50, verbose_name='Nome do produto')
    descricao_produto = models.CharField(
        max_length=255, verbose_name='Descrição do produto', blank=True)
    preco_unitario = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name='Preço unitário', blank=True, null=True)
    quantidade_disponivel = models.PositiveIntegerField(
        verbose_name='Quantidade disponíve')
    tamanho_produto = models.ForeignKey(
        TamanhoProduto, verbose_name="Tamanho do produto", on_delete=models.CASCADE)
    cor_produto = models.ForeignKey(
        CorProduto, verbose_name="Cor do produto", on_delete=models.CASCADE)
    categoria = models.ForeignKey(
        'Categoria', on_delete=models.SET_NULL, null=True, blank=True)
    foto = models.ImageField(null=True, blank=True,
                             verbose_name="Foto do produto")

    def __str__(self):
        return "{} | tam: {} | cor: {}".format(self.nome_produto, self.tamanho_produto, self.cor_produto)

    def get_absolute_url(self):
        return reverse_lazy("produto:detalhar-produto", kwargs={"pk": self.pk})
    # json

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.nome_produto,
            'estoque': self.quantidade_disponivel,
        }

    def codigo_produto_formatado(self):
        return str(self.pk).zfill(6)


class Categoria(models.Model):
    categoria = models.CharField(
        max_length=50, unique=True, verbose_name='Categoria')

    class Meta:
        ordering = ('categoria',)

    def __str__(self):
        return self.categoria

SIIC/usuarios/models.py
# from SIIC.settings import TEMPLATES
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.models import User, Group

# Create your models here.


################## CUSTOM USER MODEL ###########################
class Administrador(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not username:
            raise ValueError(
                'Forneça um nome de usuário válido para prosseguir')
        if not email:
            raise ValueError('Forneça um email válido para prosseguir')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser, PermissionsMixin):
    nome_completo = models.CharField(
        max_length=255, verbose_name='Nome completo')
    cpf = models.CharField(max_length=14, verbose_name='CPF')
    username = models.CharField(
        max_length=50, unique=True, verbose_name="Nome de usuário")
    email = models.EmailField(verbose_name='email',
                              max_length=255, unique=True)
    telefone = models.CharField(max_length=15, verbose_name='Telefone')
    date_joined = models.DateTimeField(verbose_name="data de registro",
                                       auto_now=True)
    last_login = models.DateTimeField(
        verbose_name='ultimo login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    objects = Administrador()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    class meta:
        ordering = ('username',)

SIIC/cadastros/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

SIIC/cadastros/views.py
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from usuarios.models import Usuario
from django.shortcuts import render
# Create your views here.

# lista de usuarios django
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from .models import CorProduto, TamanhoProduto, Produto, Categoria

# Controle de login
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin


# ##################################### CREATE #################################


class CorCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = CorProduto
    fields = ['cor_produto']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        form.instance.usuario_pedido = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo_pagina"] = "Cadastro de cor"
        context["titulo"] = "Cadastrar nova cor de produto"
        context["subtitulo"] = "Cadastro de cores"
        context["botao"] = "Cadastrar"
        return context


class CategoriaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Categoria
    fields = ['categoria']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        form.instance.usuario_pedido = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo_pagina"] = "Cadastro de categorias"
        context["titulo"] = "Cadastrar nova categoria de produto"
        context["subtitulo"] = "Cadastro de categorias"
        context["botao"] = "Cadastrar"
        return context


class TamanhoProdutoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = TamanhoProduto
    fields = ['tamanho_produto']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        form.instance.usuario_pedido = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo_pagina"] = "Cadastro de tamanho"
        context["titulo"] = "Cadastrar novo tamanho de produto"
        context["subtitulo"] = "Cadastro de tamanhos"
        context["botao"] = "Cadastrar"
        return context


class ProdutoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('Login')
    model = Produto
    fields = ['nome_produto', 'descricao_produto', 'preco_unitario',
              'quantidade_disponivel', 'tamanho_produto', 'cor_produto', 'categoria', 'foto']
    template_name = 'cadastros/form_produto.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        url = super().form_valid(form)
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo_pagina"] = "Cadastro de produto"
        context['titulo'] = 'Cadastrar novo produto'
        context['subtitulo'] = 'Cadastro de produtos'
        context['botao'] = 'Cadastrar'
        return context

    # ##################################### UPDATE #################################


class UsuarioUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    group_required = u"Adm"
    login_url = reverse_lazy('login')
    model = Usuario
    fields = ['username', 'email', 'nome_completo', 'cpf', 'telefone']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-usuarios')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["titulo_pagina"] = "Atualizar usuário"
        context["titulo"] = 'Atualizar dados do usuário'
        context["botao"] = 'atualizar'
        return context


class ProdutoUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    group_required = [u"Adm", u"Padrão"]
    login_url = reverse_lazy('login')
    model = Produto
    fields = ['nome_produto', 'descricao_produto', 'preco_unitario',
              'tamanho_produto', 'cor_produto', 'quantidade_disponivel', 'categoria', 'foto']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-produtos')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo_pagina"] = "Atualizar produto"
        context["titulo"] = "Editar produtos"
        context["subtitulo"] = "Editar produtos cadastrados no SIIC"
        context["botao"] = "Salvar edição"

        return context

# ##################################### DELETE #################################


class UsuarioDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy(GroupRequiredMixin, LoginRequiredMixin, 'login')
    group_required = u"Adm"
    model = Usuario
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-usuarios')


class ProdutoDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    group_required = [u"Adm", u"Padrão"]
    login_url = reverse_lazy('login')
    model = Produto
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-produtos')

# #########################LISTAR OBJETOS DE UM BANCO ##########################


class UsuarioList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = u"Adm"
    login_url = reverse_lazy('login')
    model = Usuario
    template_name = 'cadastros/listas/usuarios.html'


class ProdutoList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = [u"Adm", u"Padrão"]
    login_url = reverse_lazy('login')
    model = Produto
    template_name = 'cadastros/listas/produtos.html'


def ProdutoDetalhes(request, pk):
    obj = Produto.objects.get(pk=pk)
    template_name = 'cadastros/listas/detalhe_produto.html'
    context = {'object': obj}
    return render(request, template_name, context)


def produto_json(request, pk):
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

SIIC/cadastros/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block titulo %}
<title>Cadastros</title>
{% endblock titulo %}


{% block titulo_pagina %}
<h1 align="center">EXCLUSÃO DE REGISTRO</h1>
{% endblock titulo_pagina %}


{% block conteudo %}
<p>
</p>
<div class="jumbotron jumbotron-fluid bg-light">
    <H4 class="container" align=center>Exclusão de registro</H4>
    <p class="lead" align=center>Certifique-se que é o registro desejado</p>
    <hr>
    <form class="container" action="" method="POST">
        <p>
            Deseja excluir o registro: <b>{{ object }}</b>?
        </p>
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'listar-produtos' %}" class="btn btn-info">Voltar</a>

        <span>
            <button class="btn btn-danger" type="submit">Excluir</button>

        </span>
    </form>
    <hr>
</div>
{% endblock conteudo %}

SIIC/cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    <title>{{titulo_pagina}}</title>
{% endblock titulo %}


{% block conteudo %}
<div class="jumbotron jumbotron-fluid bg-light">
    <H4 class="container"align=center>{{titulo}}</H4>
    <p class="lead" align=center>{{subtitulo}}</p>
    <hr>
        <form class="container container-fluid" action="" method="POST" enctype="multipart/form-data">
        <h3>{{request.Pedido}}</h3>
            {% csrf_token %} <!--autenticador-->
            {{ form|crispy }} <!--formulário exibido como parágrafo-->
            <p align=right>*Campo com preenchimento obrigatório</p>
            <button class="btn btn-primary" type="submit">{{botao}}</button>
        </form>
    <hr>
</div>
{% endblock conteudo %}
{% block scripts %}
    {% comment %} Jquery_mascaras {% endcomment %}
    <script src={% static 'js/jquery.mask.min.js' %}></script>
    <script>
        $(document).ready(function(){
             $('#id_cpf').mask('000.000.000-00');
            var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };
            $('#id_telefone').mask(SPMaskBehavior, spOptions);
        });
    </script>
    {% comment %} Jquery {% endcomment %}
{% endblock scripts %}

SIIC/cadastros/templates/cadastros/form_pedidos.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    <title>Cadastros</title>
{% endblock titulo %}



{% block conteudo %}
<div class="jumbotron jumbotron-fluid bg-light">
    <H4 class="container"align=center>Cadastro de pedidos</H4>
    <p class="lead" align=center>Cadastros de pedidos realizados no sistema</p>
    <hr>
        <form class="container container-fluid" action="" method="POST">
            {% csrf_token %} <!--autenticador-->
            {{ form|crispy }} <!--formulário exibido como parágrafo-->
            <p align=right>*Campo com preenchimento obrigatório</p>
            <button class="btn btn-primary" type="submit">Cadastar</button>
        </form>
    <hr>
</div>
{% endblock conteudo %}

SIIC/cadastros/templates/cadastros/form_produto.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
<title>Cadastros</title>
{% endblock titulo %}

{% block conteudo %}
<div class="jumbotron jumbotron-fluid bg-light">
    <H4 class="container" align=center>Cadastro de produtos no SIIC</H4>
    <p class="lead" align=center>Cadastro de produtos</p>
    <hr>
    <form class="container container-fluid" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-8 mb-0">
                    {{form.nome_produto|as_crispy_field}}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{form.preco_unitario|as_crispy_field}}
                </div>
            </div>
                    {{form.descricao_produto|as_crispy_field}}
            <div class="row">
                <div class="form-group col-md-3 mb-0">
                    {{form.categoria|as_crispy_field}}
                </div>
                <div class="form-group col-md-3 mb-0">
                    {{form.tamanho_produto|as_crispy_field}}
                </div>
                <div class="form-group col-md-3 mb-0">
                    {{form.cor_produto|as_crispy_field}}
                </div>
                <div class="form-group col-md-3 mb-0">
                    {{form.quantidade_disponivel|as_crispy_field}}
                </div>               
            </div>
            <div class="lign-center">
                {{form.foto|as_crispy_field}}
            </div>
        {% comment %} {{ form|crispy }} {% endcomment %}
        <!--formulário exibido como parágrafo-->
        <p align=left>*Campo com preenchimento obrigatório</p>
        <button class="btn btn-primary" type="submit">Cadastar</button>
    </form>
    <hr>
</div>
{% endblock conteudo %}
{% block scripts %}
    {% comment %} Jquery_mascaras {% endcomment %}
    <script src={% static 'js/jquery.mask.min.js' %}></script>
    <script>
        $(document).ready(function(){
             $('#id_cpf').mask('000.000.000-00');
            $('#id_preco_unitario').mask('000.00,00', {placeholder: "R$ "});
            var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

            $('#id_telefone').mask(SPMaskBehavior, spOptions);
        });
    </script>
    {% comment %} Jquery {% endcomment %}
{% endblock scripts %}

SIIC/cadastros/templates/cadastros/form_user.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
<title>{{titulo_pagina}}</title>
{% endblock titulo %}

{% block conteudo %}
<div class="jumbotron jumbotron-fluid bg-light">
    <H4 class="container" align=center>Cadastro de usuários</H4>
    <p class="lead" align=center>Cadastro dos usuários do SIIC - Sistema Integrado de Inventário e Controle</p>
    <hr>
    <form class="container container-fluid" action="" method="POST">
        {% csrf_token %}
        Formulario personalizado
            <div class="row">
                <div class="form-group col-md-4 mb-0">
                    {{form.username|as_crispy_field}}
                </div>
                <div class="form-group col-md-8 mb-0">
                    {{form.email|as_crispy_field}}
                </div>
            </div>
                {{form.nome_completo|as_crispy_field}}
            <div class="row">
                <div class="form-group col-md-6 mb-0">
                    {{form.cpf|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.telefone|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 mb-0">
                    {{form.password1|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.password2|as_crispy_field}}
                </div>
            </div>
        {% comment %} {{ form|crispy }} {% endcomment %}
        <!--formulário exibido como parágrafo-->
        <p align=left>*Campo com preenchimento obrigatório</p>
        <button class="btn btn-primary" type="submit">Cadastar</button>
    </form>
    <hr>
</div>
{% endblock conteudo %}
{% block scripts %}
    {% comment %} Jquery_mascaras {% endcomment %}
    <script src={% static 'js/jquery.mask.min.js' %}></script>
    <script>
        $(document).ready(function(){
             $('#id_cpf').mask('000.000.000-00');
            var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

            $('#id_telefone').mask(SPMaskBehavior, spOptions);
        });
    </script>
    {% comment %} Jquery {% endcomment %}
{% endblock scripts %}